name: unifying-physics
version: 0.1.0.0
dependencies:
- base >= 4.18 && < 4.19
- ad >= 4.4

library:
  exposed-modules: ClassicalLimit, QuantumLogic, RepresentationEquivalence
  source-dirs: src

executables:
  unifying-physics:
    main: Main.hs
    source-dirs: .
